### ISSUE TITLE
Entity class

### ISSUE THREAD

**Issue by Drakon4ik-Coder** [Drakon4ik-Coder/WraithBound#1]
Create entity class

**Comment by dsk1ra** [comment]
**Entity.h**: 
Created a base class Entity to represent game entities with a shape and position.
Added protected members _shape (unique pointer to the shape) and _position (position of the entity).
Implemented a constructor to initialize the entity with a shape.
Deleted the default constructor and provided a default virtual destructor.
Added virtual methods Update and Render for updating the entity's state and rendering it, respectively.
Implemented methods to get, set, and move the entity's position.

**Entity.cpp**:
Implemented the getPosition, setPosition, and move methods to manage the entity's position.
Implemented the Update method to update the shape's position.
Defined the constructor to initialize the entity with a shape.
