### ISSUE TITLE
Player class

### ISSUE THREAD

**Issue by Drakon4ik-Coder** [Drakon4ik-Coder/WraithBound#2]
Create Player class

**Comment by dsk1ra** [comment]
**Player.h:**
Created a Player class derived from Entity to represent the player entity.
Added a private member _speed to store the player's speed.
Implemented a constructor to initialize the player with a speed and shape.
Overrode the Update method to handle player-specific updates based on keyboard input.
Overrode the Render method to draw the player on the window.

**Player.cpp:**
Implemented the Update method to move the player in four directions based on keyboard input (WASD) and call the base class update.
Defined the constructor to initialize the player with a speed and shape and set the shape's origin. (Placeholder - magenta circle with radius 25.f)
Implemented the Render method to draw the player's shape on the window.
